//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adsfile
    {
        public int aid { get; set; }
        public string filename { get; set; }
        public string ausername { get; set; }
        public string aemail { get; set; }
        public string astatus { get; set; }
    }
}
