//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class domain_u
    {
        public int domain_id { get; set; }
        public string domain_name { get; set; }
        public Nullable<int> domain_user { get; set; }
        public string domain_status { get; set; }
    
        public virtual user user { get; set; }
    }
}
