//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class domainEntities : DbContext
    {
        public domainEntities()
            : base("name=domainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adsfile> adsfiles { get; set; }
        public virtual DbSet<domain_u> domain_u { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<support> supports { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<userprofile> userprofiles { get; set; }
        public virtual DbSet<tag> tags { get; set; }
        public virtual DbSet<admintag> admintags { get; set; }
        public virtual DbSet<adstxt> adstxts { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<admincsvtag> admincsvtags { get; set; }
        public virtual DbSet<usertag> usertags { get; set; }
        public virtual DbSet<payment_options> payment_options { get; set; }
        public virtual DbSet<Revenue> Revenues { get; set; }
    }
}
