//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class support
    {
        public int sid { get; set; }
        public string ssubject { get; set; }
        public string smessage { get; set; }
        public string sfile { get; set; }
        public string susername { get; set; }
        public string suseremail { get; set; }
    }
}
