//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tag
    {
        public int tid { get; set; }
        public string username { get; set; }
        public string userid { get; set; }
        public Nullable<int> domainid { get; set; }
    }
}
