//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.domain_u = new HashSet<domain_u>();
            this.userprofiles = new HashSet<userprofile>();
        }
    
        public int userid { get; set; }
        public string username { get; set; }
        public string useremail { get; set; }
        public string userpass { get; set; }
        public Nullable<int> role_id { get; set; }
        public string userphone { get; set; }
        public string skype_id { get; set; }
        public string domain { get; set; }
        public string Daily_pages_views { get; set; }
        public string status { get; set; }
        public string ecode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<domain_u> domain_u { get; set; }
        public virtual role role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userprofile> userprofiles { get; set; }
    }
}
