//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userprofile
    {
        public int proid { get; set; }
        public string proname { get; set; }
        public string proemail { get; set; }
        public string proimage { get; set; }
        public string propass { get; set; }
        public Nullable<int> users_id { get; set; }
    
        public virtual user user { get; set; }
    }
}
